---
driver:
  name: docker

provisioner:
  name: salt_solo
  formula: infratest
  state_top:
    base:
      "*":
        - infratest

platforms:
  - name: debian-8

suites:
  - name: default

  - name: custom
    provisioner:
      pillars-from-files:
        infratest.sls: pillar-custom.sls
      pillars:
        top.sls:
          base:
            "*":
              - infratest
