sudo: required

language: ruby

bundler_args: --without='vagrant linode'

services:
  - docker

env:
  matrix:
  - INSTANCE=default
  - INSTANCE=custom

script:
  - KITCHEN_LOCAL_YAML=.kitchen-docker.yml kitchen verify ${INSTANCE}

after_failure: cat docker_daemon.log
