addons:
  code_climate:
    repo_token: 84558499f32ed83e00b961615a54568499bcf97318699d8fc37babf166392e1f

sudo: required

language: ruby

bundler_args: --without='vagrant linode'

services:
  - docker

env:
  matrix:
  - INSTANCE=default
  - INSTANCE=custom

script:
  - KITCHEN_LOCAL_YAML=.kitchen-docker.yml kitchen verify ${INSTANCE}
  - bundle exec rake

after_script:
  - docker images
  - docker ps -a
  - cat .kitchen/logs/kitchen.log

after_failure: cat docker_daemon.log
